#!/bin/bash

bspc config focused_border_color "#ff8c00"
bspc config normal_border_color "#2e3440"
bspc config presel_feedback_color "#ff8c00"

bspc config border_width 2
bspc config window_gap 12

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop='^8' state=floating follow=on
